// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexa.Transactions.Infrastructure.EntityFramework;

#nullable disable

namespace Nexa.Transactions.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(TransactionDbContext))]
    [Migration("20250625150734_TransferMigrations")]
    partial class TransferMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Transactions")
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nexa.Transactions.Domain.Transfers.Transfer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("WalletId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Transfers", "Transactions");

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Nexa.Transactions.Domain.Transfers.TransferView", b =>
                {
                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Direction")
                        .HasColumnType("int");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReciverId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("WalletId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("Transfers", "Transactions");
                });

            modelBuilder.Entity("Nexa.Transactions.Domain.Transfers.AchTransfer", b =>
                {
                    b.HasBaseType("Nexa.Transactions.Domain.Transfers.Transfer");

                    b.Property<string>("CounterPartyId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.HasIndex("CounterPartyId");

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("Nexa.Transactions.Domain.Transfers.NetworkTransfer", b =>
                {
                    b.HasBaseType("Nexa.Transactions.Domain.Transfers.Transfer");

                    b.Property<string>("ReciverId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasIndex("ReciverId");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Nexa.Transactions.Domain.Transfers.WireTransfer", b =>
                {
                    b.HasBaseType("Nexa.Transactions.Domain.Transfers.Transfer");

                    b.Property<string>("CounterPartyId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.HasIndex("CounterPartyId");

                    b.ToTable("Transfers", "Transactions", t =>
                        {
                            t.Property("CounterPartyId")
                                .HasColumnName("WireTransfer_CounterPartyId");

                            t.Property("Direction")
                                .HasColumnName("WireTransfer_Direction");
                        });

                    b.HasDiscriminator().HasValue(10);
                });
#pragma warning restore 612, 618
        }
    }
}
