// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexa.CustomerManagement.Infrastructure.EntityFramework;

#nullable disable

namespace Nexa.CustomerManagement.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(CustomerManagementDbContext))]
    [Migration("20251020005422_RemoveObsoletePropertiesAndUpdateTheExistMigration")]
    partial class RemoveObsoletePropertiesAndUpdateTheExistMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("CustomerManagement")
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nexa.CustomerManagement.Domain.Customers.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FintechCustomerId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("KycCustomerId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Customers", "CustomerManagement");
                });

            modelBuilder.Entity("Nexa.CustomerManagement.Domain.Reviews.KycReview", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("KycCheckId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("KycLiveVideoId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("Outcome")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("KycCheckId");

                    b.HasIndex("KycLiveVideoId");

                    b.ToTable("KycReviews", "CustomerManagement");
                });

            modelBuilder.Entity("Nexa.CustomerManagement.Domain.Customers.Customer", b =>
                {
                    b.OwnsOne("Nexa.CustomerManagement.Domain.Customers.CustomerInfo", "Info", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<DateTime>("BirthDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<int>("Gender")
                                .HasColumnType("int");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.HasKey("Id");

                            b1.ToTable("CustomersInfos", "CustomerManagement");

                            b1.WithOwner()
                                .HasForeignKey("Id");

                            b1.OwnsOne("Nexa.CustomerManagement.Domain.Customers.Address", "Address", b2 =>
                                {
                                    b2.Property<string>("CustomerInfoId")
                                        .HasColumnType("nvarchar(256)");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("nvarchar(3)");

                                    b2.Property<string>("PostalCode")
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)");

                                    b2.Property<string>("State")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)");

                                    b2.Property<string>("StreetLine")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("nvarchar(500)");

                                    b2.Property<string>("ZipCode")
                                        .HasMaxLength(10)
                                        .HasColumnType("nvarchar(10)");

                                    b2.HasKey("CustomerInfoId");

                                    b2.ToTable("CustomersInfos", "CustomerManagement");

                                    b2.WithOwner()
                                        .HasForeignKey("CustomerInfoId");
                                });

                            b1.Navigation("Address")
                                .IsRequired();
                        });

                    b.OwnsOne("Nexa.CustomerManagement.Domain.Documents.Document", "Document", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<string>("IssuingCountry")
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.Property<string>("KycDocumentId")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<string>("KycReviewId")
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)");

                            b1.Property<int>("Status")
                                .HasColumnType("int");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("KycDocumentId");

                            b1.HasIndex("KycReviewId");

                            b1.ToTable("Documents", "CustomerManagement");

                            b1.WithOwner()
                                .HasForeignKey("Id");

                            b1.HasOne("Nexa.CustomerManagement.Domain.Reviews.KycReview", null)
                                .WithMany()
                                .HasForeignKey("KycReviewId");

                            b1.OwnsMany("Nexa.CustomerManagement.Domain.Documents.DocumentAttachment", "Attachments", b2 =>
                                {
                                    b2.Property<string>("DocumentId")
                                        .HasColumnType("nvarchar(256)");

                                    b2.Property<string>("Id")
                                        .HasMaxLength(256)
                                        .HasColumnType("nvarchar(256)");

                                    b2.Property<string>("ContentType")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)");

                                    b2.Property<string>("FileName")
                                        .IsRequired()
                                        .HasMaxLength(256)
                                        .HasColumnType("nvarchar(256)");

                                    b2.Property<string>("KycAttachmentId")
                                        .HasMaxLength(256)
                                        .HasColumnType("nvarchar(256)");

                                    b2.Property<int>("Side")
                                        .HasColumnType("int");

                                    b2.Property<long>("Size")
                                        .HasColumnType("bigint");

                                    b2.HasKey("DocumentId", "Id");

                                    b2.HasIndex("KycAttachmentId");

                                    b2.ToTable("DocumentsAttachments", "CustomerManagement");

                                    b2.WithOwner()
                                        .HasForeignKey("DocumentId");
                                });

                            b1.Navigation("Attachments");
                        });

                    b.Navigation("Document");

                    b.Navigation("Info");
                });

            modelBuilder.Entity("Nexa.CustomerManagement.Domain.Reviews.KycReview", b =>
                {
                    b.HasOne("Nexa.CustomerManagement.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
